ToDoList/Models/Category.cs
using System.Collections.Generic;

namespace ToDoList.Models
{
    public class Category
    {
        public void Catergory()
        {
            this.Items = new HashSet<Item>();
        }
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Item> Items { get; set; }


    }
}

ToDoList/Models/Item.cs
using System.Collections.Generic;
using MySql.Data.MySqlClient;

namespace ToDoList.Models
{
  public class Item
  {

      public int ItemId { get; set; }
      public string Description { get; set; }
      public int CategoryId { get; set; }
      public virtual Category Category { get; set; }

  }
}

ToDoList/Models/ToDoListContext.cs
using Microsoft.EntityFrameworkCore;

namespace ToDoList.Models
{
  public class ToDoListContext : DbContext
  {
    public virtual DbSet<Category> Categories { get; set; }
    public DbSet<Item> Items {get; set; }
    public ToDoListContext(DbContextOptions options) : base(options) { }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

ToDoList/Controllers/CategoriesController.cs
using System.Collections.Generic;
using System;
using Microsoft.AspNetCore.Mvc;
using ToDoList.Models;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ToDoList.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ToDoListContext _db;
        public CategoriesController(ToDoListContext db)
        {
            _db = db;
        }

        public ActionResult Index()
        {
            List<Category> model = _db.Categories.ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Category category)
        {
            _db.Categories.Add(category);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
    
}

ToDoList/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace ToDoList.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

      [Route("/favorite_photos")]
      public ActionResult FavoritePhotos()
      {
        return View();
      }
      
    }
}

ToDoList/Controllers/ItemsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ToDoList.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ToDoList.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ToDoListContext _db;
        public ItemsController(ToDoListContext db)
        {
            _db = db;
        }
        public ActionResult Index()
        {
            List<Item> model = _db.Items.Include(items => items.Category).ToList();
            return View(model);
        }

        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Item item)
        {
            _db.Items.Add(item);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            Item thisItem = _db.Items.FirstOrDefault(items => items.ItemId == id);
            return View(thisItem);
        }

        public ActionResult Edit(int id)
        {
            var thisItem = _db.Items.FirstOrDefault(items => items.ItemId == id);
            ViewBag.CategoryId = new SelectList(_db.Categories, "CategoryId", "Name");
            return View(thisItem);
;        }

        [HttpPost]
        public ActionResult Edit(Item item)
        {
            _db.Entry(item).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var thisItem = _db.Items.FirstOrDefault(items => items.ItemId == id);
            return View(thisItem);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisItem = _db.Items.FirstOrDefault(items => items.ItemId == id);
            _db.Items.Remove(thisItem);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

ToDoList/Views/Categories/Create.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Category

<h3>Add new Category</h3>

@using(Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  <input type="submit" value="Add new Category">
}

<p>@Html.ActionLink("Go back to all Categories", "Index")</p>

ToDoList/Views/Categories/Index.cshtml
@{
  Layout = "_Layout";
}

@using ToDoList.Models;
@model List<ToDoList.Models.Category>

@if ( Model.Count == 0)
{
  <h3>There are no categories created yet!</h3>
}

@foreach (Category category in Model)
{
  <li>@Html.ActionLink($"{category.Name}", "Details", new {id = category.CategoryId})</li>
}

<p>@Html.ActionLink("Home", "Index", "Home")</p>

ToDoList/Views/Home/FavoritePhotos.cshtml
  <!DOCTYPE html>
  <html>
    <head>
      <title>My To-Do List!</title>
      <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    </head>
    <body>
      <h1>Favorite Traveling Photos</h1>
      <ul>
        <li><img src='~/img/photo1.jpg'/></li>
        <li><img src='~/img/photo2.jpg'/></li>
        <li><img src='~/img/photo3.jpg'/></li>
      </ul>
    </body>
  </html>

ToDoList/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
<div class="container">
  <h1>Welcome to the To Do List!</h1>
  <p>@Html.ActionLink("See all items", "Index", "Items")</p>
  <p>@Html.ActionLink("See all categories", "Index", "Categories")</p>
</div>

ToDoList/Views/Items/Create.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Item

<div class="container">
  <h4>Add a new task</h4>
  @using(Html.BeginForm())
  {
    @Html.LabelFor(model => model.Description)
    @Html.TextBoxFor(model => model.Description)

    @Html.LabelFor(model => model.Category)
    @Html.DropDownList("CategoryId")
    
    <input type="submit" value="Add new task"/>
  }
  <p>@Html.ActionLink("Show all the items", "Index")</p>
</div>

ToDoList/Views/Items/Delete.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Item

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

ToDoList/Views/Items/Details.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Item

<div class="container">
  <h2>Item Details</h2>
  <hr />
  <h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>
  <p>@Html.ActionLink("Back to List", "Index")</p>
  <p>@Html.ActionLink("Edit Item", "Edit", new { id = Model.ItemId})</p>
  <p>@Html.ActionLink("Delete Item", "Delete", new{ id = Model.ItemId })</p>
</div>

ToDoList/Views/Items/Edit.cshtml
@{
  Layout = "_Layout";
}

@model ToDoList.Models.Item

<h2>Edit</h2>

<h4>Edit this task: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ItemId)

  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)

  @Html.LabelFor(model => model.Category)
  @Html.DropDownList("CategoryId")

  <input type="submit" value="Save" />
}

<p>@Html.ActionLink("Back to List", "Index")</p>
<p>@Html.ActionLink("Edit next Item", "Edit", new { id = Model.ItemId+1 })</p>

ToDoList/Views/Items/Index.cshtml
@{
  Layout = "_Layout";
}

@using ToDoList.Models;
@model List<ToDoList.Models.Item>

<div class="container">
  <h1>Items</h1>

  @if (@Model.Count == 0)
  {
    <h3>No items have been added yet!</h3>
  }

  @foreach (Item item in Model)
  {
    <li>@Html.ActionLink($"{item.Description}", "Details", new { id = item.ItemId}) | @item.Category.Name
    </li>
  }

  <p>@Html.ActionLink("Add new item", "Create")</p>
  <p>@Html.ActionLink("Home", "Index", "Home")</p>
</div>

ToDoList/Views/Shared/Footer.cshtml
<div id="footer">Bottom div content</div>

ToDoList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>My To-Do List!</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
    @* @Html.Partial("Footer") *@
  </body>
</html>